"""Added appointments table

Revision ID: 7b7dbf744588
Revises: 9a0d2816e4b3
Create Date: 2026-06-07 23:34:53.627692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7dbf744588'
down_revision = '9a0d2816e4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_medicine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_medicine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visit_id', sa.INTEGER(), nullable=True),
    sa.Column('medicine_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=100), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=100), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
